### ISSUE TITLE
Finish button is not clicking always

### ISSUE THREAD

**Issue by sarithasmart** [Omenia/robotframework-whitelibrary#143] opened 2019-06-20 21:28 UTC
**Describe the bug**
I have a code to uninstall the product. after uninstall is done, click on finish button. But white is not clicking always finish button. 

**To Reproduce**

I am adding wait to view whether Finish button is enabled during the installation. 
after it is enable i have used below code to click on Finish button
yeti.Click Object With Mouse    xpath=//button[@Name='Finish Enter']**

**Expected behavior**
It has to click on Finish button.

**Screenshots**

![image](https://user-images.githubusercontent.com/52052793/59882632-00c45d80-9370-11e9-89aa-62e25d8f5711.png)

**Desktop (please complete the following information):**
 - Windows 10
 - 

**Smartphone (please complete the following information):**

**Additional context**
Focus in going on to Finish button, but white is not clicking on the Finish button

**Comment by rasjani** [comment] 2019-06-24 05:27
Quickly going thru whitelibrary's code, i can't spot  `Click Object With Mouse` keyword. Are you sure that the issue is actually in this package and not in some internal or 3rd party wrapper ?

**Comment by sarithasmart** [comment] 2019-06-24 19:35
It is a white keyword. code for the same:


 public void Click_Object_With_Mouse(String elementDescription)
        {
            try
            { 
                IUIItem ui = findUIObject(elementDescription);

                ui.Click();
            }
            catch (Exception ex)
            {
                lastError = ex.Message + " Note for buttons on Modal Dialog box, you have to use CLICK_MODAL_BUTTON_WITH_MOUSE";
            }
         }

**Comment by rasjani** [comment] 2019-06-25 12:43
@sarithasmart - it almost feels like you are not talking about about robotframework-whitelibrary but about this project: https://github.com/jatalahd/WhiteRobotLibrary  perhaps ? Code you paste above does not ship with ours and is not even in language most of our wrapper is done, eg python. That code is either java or c#. 

If you feel that the issue is still indeed without robotframework-whitelibrary, could you share a snippet of your robot code (including resource lines and suite setups/teardowns) and verbose logging of the execution.

**Comment by rasjani** [comment] 2019-07-01 11:34
Closing for now.

**Closed by rasjani** 2019-07-01 11:34 UTC
