### ISSUE TITLE
Unable to click on radio button inside a pane.

### ISSUE THREAD

**Issue by AnnneN** [Omenia/robotframework-whitelibrary#144] opened 2019-06-25 09:34 UTC
Hi,

I am unable to click on the radio button inside a pane using below statement

Attach Window  title:New
Select Radio Button   text:S1

If I inspect, the structure looks below:
S1(window)
                 |__tab
                           |__pane(p1)
                                            |__S1(radio button)

Below path:
![image](https://user-images.githubusercontent.com/34029266/60087523-cc2f1800-975a-11e9-9383-b89c7a22ff74.png)

Could  you pls help here.

**Comment by rasjani** [comment] 2019-06-25 12:55
I'd assume one has to select the tab first before one can interact with the ui elements contained within it.  See `Select Tab Page` and `Select Tab Page By Index` @ http://omenia.github.io/robotframework-whitelibrary/keywords.html

**Comment by NainaDhiman** [comment] 2019-06-25 16:07
Hi Jani, 
I tried clicking on tab first and it didnt worked with above commands , though worked with "Click Item".
Here control type for tab =tab item

Also I noticed when I clicked on tab, pane (p1) as above appears in which radio button is located.
I believe ..i need to select pane, could you pls help.
ControlType:	UIA_PaneControlTypeId (0xC371)
LocalizedControlType:	"pane"

**Comment by NainaDhiman** [comment] 2019-06-26 04:21
Hello Jani, 
I am able to click in tab using Select Tab by Index but struggling to click pane and radio button.
![image](https://user-images.githubusercontent.com/34029266/60150814-da7f4180-97f7-11e9-9b7f-9939b281515e.png)

Could you pls advise how to click inside a pane using White Library keywords?

**Comment by NainaDhiman** [comment] 2019-06-26 05:10
Placing clear shot 
![image](https://user-images.githubusercontent.com/34029266/60152536-7ad86480-97fe-11e9-9431-23693df7f152.png)
Here ticked in Blue are achieved while yellow ones are pending.
Could you pls guide how to click on "Pane" and then transverse to radio button.

Thanks
Naina

**Comment by rasjani** [comment] 2019-06-26 10:17
There's a good chance that this does not work. Ive read few issues describing similar scenario and even with directly using teststack white, only way forward was doing mouse interactions with absolute coordinates.  I might be wrong though.

However, in order to rule that out, could you share the code so far that you tried to use to reach the output panne and the context within it ..  Also, after selecting the "Output" panel from tab control, are you able to interact with the edit and text fields (Eg, ruling out that its the interaction within the pane that starts with D where the issue is..

**Comment by NainaDhiman** [comment] 2019-06-26 12:29
Again clear shot
![image](https://user-images.githubusercontent.com/34029266/60179547-88f8a600-983b-11e9-977e-1c6d898b14a0.png)

Thanks for looking into this.
I noticed that Output panel appears only when I click on Output tab(dynamic in nature and true for other tabs too).
In application Output panel is visible after clicking in output tab but strange is that they lie in same level at page level.
For clicking on Output tab, I am using simple statement as below:
Click Item   text:Output

If I use Select Tab by Index, it also works ..here I have to use ""tab(1 level up all tabs)
Select Tab by Index   id:7890   5

I suspect that m not able to go into Output pane due to which not able to click S radio button.
Any pointers to help here.

**Comment by AnnneN** [comment] 2019-06-27 14:36
Hi Jani,

Any updates on above issue?

Thanks
Naina

**Comment by rasjani** [comment] 2019-06-28 11:43
As said in previous comment, most likely feature is not currently supported and by the looks of it might require workarounds even in pure teststack white.   I asked a question to rule this out, did you try, for example entering text into "text" and "edit" fields ..  For now, i would just go with using mouse events. Which again, are not supported by us at the moment but wouldnt be too hard to implement.  Patches welcome.

**Comment by rasjani** [comment] 2019-07-01 18:10
Closing this for now. Side note to @eeter - maybe we should check if there’s something we could add regarding tabs and dynamic content.

**Closed by rasjani** 2019-07-01 18:10 UTC
Labels: question
